services:
  target-architecture:
    container_name: software-architecture-documentation-target
    image: structurizr/lite
    volumes:
      - ./target:/usr/local/structurizr
    ports:
      - "8081:8080"

#  baseline-architecture:
#    container_name: software-architecture-documentation-baseline
#    image: structurizr/lite
#    volumes:
#      - ./workspace:/usr/local/structurizr
#    ports:
#      - "8082:8080"